import type { LucideIcon } from 'lucide-react'
import type { CategoryType } from '@/types/database'
import {
  Anchor,
  Apple,
  Armchair,
  Baby,
  Backpack,
  Bandage,
  Banknote,
  Bath,
  Bed,
  Beer,
  Bike,
  Bird,
  Blender,
  Bone,
  Book,
  BookHeart,
  BookOpen,
  Brain,
  Briefcase,
  BriefcaseMedical,
  Brush,
  Building,
  Bus,
  BusFront,
  Cake,
  Camera,
  Candy,
  Car,
  CarFront,
  Cat,
  Clapperboard,
  Coffee,
  Coins,
  Compass,
  CreditCard,
  Croissant,
  Crown,
  CupSoda,
  Dog,
  DollarSign,
  Donut,
  Droplet,
  Droplets,
  Drum,
  Dumbbell,
  Ear,
  Ellipsis,
  Eye,
  FerrisWheel,
  Film,
  Fish,
  Flame,
  FlameKindling,
  Flower,
  Flower2,
  Footprints,
  Fuel,
  Gamepad,
  Gem,
  Gift,
  GlassWater,
  GraduationCap,
  Hand,
  HandCoins,
  HandHeart,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  Heater,
  Home,
  Hotel,
  House,
  IceCream,
  Key,
  Lamp,
  Leaf,
  LeafyGreen,
  Landmark,
  Laptop,
  Library,
  LibraryBig,
  Lightbulb,
  Lock,
  Luggage,
  Map,
  Microwave,
  Microscope,
  Milk,
  Monitor,
  MirrorRound,
  Moon,
  Mountain,
  Music,
  Package,
  Palette,
  ParkingSquare,
  PartyPopper,
  PawPrint,
  Pen,
  PersonStanding,
  Phone,
  Piano,
  PiggyBank,
  Pill,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  Plug,
  Popsicle,
  Rabbit,
  Receipt,
  Refrigerator,
  Ribbon,
  Rocket,
  RollerCoaster,
  Salad,
  School,
  Scissors,
  Shield,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  ShowerHead,
  Smartphone,
  Snowflake,
  Sofa,
  Sparkle,
  Sparkles,
  SprayCan,
  Sprout,
  Stethoscope,
  Sun,
  Sunrise,
  Syringe,
  Tent,
  TestTube,
  Thermometer,
  Toilet,
  ToyBrick,
  Train,
  TramFront,
  TreePine,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  Utensils,
  UtensilsCrossed,
  Wallet,
  WandSparkles,
  WashingMachine,
  Watch,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react'

export interface CategoryIconGroup {
  label: string
  icons: Record<string, LucideIcon>
  /** 适用于哪些分类类型；缺省视为仅支出 */
  types?: CategoryType[]
}

/**
 * 分类图标预设（与 seed 数据一致；数据库存 key）
 * 按生活场景分组，方便在添加分类弹窗中快速找到合适的图标
 */
export const CATEGORY_ICON_GROUPS: CategoryIconGroup[] = [
  {
    label: '餐饮',
    icons: {
      utensils: Utensils,
      'utensils-crossed': UtensilsCrossed,
      coffee: Coffee,
      'cup-soda': CupSoda,
      milk: Milk,
      beer: Beer,
      wine: Wine,
      cake: Cake,
      'ice-cream': IceCream,
      donut: Donut,
      candy: Candy,
      popsicle: Popsicle,
      croissant: Croissant,
      apple: Apple,
      salad: Salad,
      flame: Flame,
    },
  },
  {
    label: '交通',
    icons: {
      car: Car,
      'car-front': CarFront,
      bus: Bus,
      'bus-front': BusFront,
      'tram-front': TramFront,
      train: Train,
      bike: Bike,
      fuel: Fuel,
      'parking-square': ParkingSquare,
      plane: Plane,
      'plane-takeoff': PlaneTakeoff,
      'plane-landing': PlaneLanding,
    },
  },
  {
    label: '住房家居',
    icons: {
      home: Home,
      house: House,
      bed: Bed,
      bath: Bath,
      'shower-head': ShowerHead,
      toilet: Toilet,
      sofa: Sofa,
      armchair: Armchair,
      lamp: Lamp,
      refrigerator: Refrigerator,
      'washing-machine': WashingMachine,
      microwave: Microwave,
      blender: Blender,
      wrench: Wrench,
      key: Key,
    },
  },
  {
    label: '水电燃气',
    icons: {
      zap: Zap,
      droplet: Droplet,
      'flame-kindling': FlameKindling,
      wifi: Wifi,
      plug: Plug,
      heater: Heater,
      lightbulb: Lightbulb,
    },
  },
  {
    label: '通讯数码',
    icons: {
      smartphone: Smartphone,
      phone: Phone,
      laptop: Laptop,
      monitor: Monitor,
      tv: Tv,
      watch: Watch,
      headphones: Headphones,
      camera: Camera,
    },
  },
  {
    label: '医疗',
    icons: {
      'heart-pulse': HeartPulse,
      pill: Pill,
      stethoscope: Stethoscope,
      'briefcase-medical': BriefcaseMedical,
      syringe: Syringe,
      bandage: Bandage,
      'test-tube': TestTube,
      microscope: Microscope,
      brain: Brain,
      eye: Eye,
      ear: Ear,
      bone: Bone,
      thermometer: Thermometer,
    },
  },
  {
    label: '养生丽人',
    icons: {
      leaf: Leaf,
      'leafy-green': LeafyGreen,
      'glass-water': GlassWater,
      moon: Moon,
      sunrise: Sunrise,
      'person-standing': PersonStanding,
      'mirror-round': MirrorRound,
      'spray-can': SprayCan,
      droplets: Droplets,
      brush: Brush,
      palette: Palette,
      'wand-sparkles': WandSparkles,
      crown: Crown,
      ribbon: Ribbon,
      hand: Hand,
      'flower-2': Flower2,
      sparkle: Sparkle,
    },
  },
  {
    label: '娱乐运动',
    icons: {
      clapperboard: Clapperboard,
      film: Film,
      gamepad: Gamepad,
      music: Music,
      piano: Piano,
      drum: Drum,
      'roller-coaster': RollerCoaster,
      'ferris-wheel': FerrisWheel,
      'party-popper': PartyPopper,
      dumbbell: Dumbbell,
      footprints: Footprints,
      sparkles: Sparkles,
    },
  },
  {
    label: '教育',
    icons: {
      'graduation-cap': GraduationCap,
      book: Book,
      'book-open': BookOpen,
      'book-heart': BookHeart,
      school: School,
      library: Library,
      'library-big': LibraryBig,
      pen: Pen,
    },
  },
  {
    label: '购物',
    icons: {
      'shopping-bag': ShoppingBag,
      'shopping-cart': ShoppingCart,
      package: Package,
      shirt: Shirt,
      gem: Gem,
      scissors: Scissors,
    },
  },
  {
    label: '人情礼物',
    icons: {
      gift: Gift,
      heart: Heart,
      'hand-heart': HandHeart,
      'heart-handshake': HeartHandshake,
    },
  },
  {
    label: '旅行',
    icons: {
      luggage: Luggage,
      backpack: Backpack,
      hotel: Hotel,
      tent: Tent,
      map: Map,
      compass: Compass,
      mountain: Mountain,
      anchor: Anchor,
      ship: Ship,
      umbrella: Umbrella,
      sun: Sun,
      snowflake: Snowflake,
    },
  },
  {
    label: '宠物',
    icons: {
      'paw-print': PawPrint,
      cat: Cat,
      dog: Dog,
      bird: Bird,
      fish: Fish,
      rabbit: Rabbit,
    },
  },
  {
    label: '孩子',
    icons: {
      baby: Baby,
      'toy-brick': ToyBrick,
    },
  },
  {
    label: '园艺植物',
    icons: {
      sprout: Sprout,
      'tree-pine': TreePine,
      flower: Flower,
    },
  },
  {
    label: '财务',
    types: ['expense', 'income'],
    icons: {
      banknote: Banknote,
      wallet: Wallet,
      'piggy-bank': PiggyBank,
      coins: Coins,
      'hand-coins': HandCoins,
      'credit-card': CreditCard,
      receipt: Receipt,
      'dollar-sign': DollarSign,
      landmark: Landmark,
      building: Building,
      trophy: Trophy,
      'trending-up': TrendingUp,
      briefcase: Briefcase,
      rocket: Rocket,
    },
  },
  {
    label: '保障',
    icons: {
      shield: Shield,
      lock: Lock,
    },
  },
  {
    label: '其他',
    types: ['expense', 'income'],
    icons: {
      ellipsis: Ellipsis,
    },
  },
]

/** 所有图标的扁平映射（数据库存 key，CategoryIcon 用 key 查组件） */
export const CATEGORY_ICONS: Record<string, LucideIcon> = Object.assign(
  {},
  ...CATEGORY_ICON_GROUPS.map((group) => group.icons),
)

/** 付款方式预设 */
export const PAY_METHODS = ['现金', '微信', '支付宝', '银行卡', '信用卡'] as const

export function CategoryIcon({
  icon,
  color,
  className,
}: {
  icon: string
  color?: string
  className?: string
}) {
  const Icon = CATEGORY_ICONS[icon] ?? Ellipsis
  return <Icon className={className} style={{ color }} />
}
